[build]
base = "/"
command = "npx vite build"
publish = "dist/"

[[redirects]]
from = "/components"
status = 200
to = "/index.html"

[[redirects]]
from = "/hooks"
status = 200
to = "/index.html"

[[redirects]]
from = "/settings"
status = 200
to = "/index.html"
